Larusso/unity-version-manager

- install/uvm-install/src/main.rs
- install/uvm_install_core/src/lib.rs
Unity changed the component name of the windows support component from
`windows` to `windows-mono` for all versions > 2018
> Fix windows support package cask for unity > 2018

- commands/uvm-clear/src/lib.rs
- commands/uvm-launch/src/main.rs
- uvm_core/proptest-regressions/unity/installation.txt
- uvm_core/proptest-regressions/unity/mod.txt
- uvm_core/src/error.rs
- uvm_core/src/lib.rs
- uvm_core/src/result.rs
- uvm_core/src/unity/current_installation.rs
- uvm_core/src/unity/installation.rs
- uvm_core/src/unity/mod.rs
This patch introduces a custom Error Enum `UvmError` together with a
`result::Result` type defined in `uvm_core` to wrap `io::Error` and
`ParseVersionError`.
> Add UvmError a error wrapper to replace usage of io::Result

- uvm_core/Cargo.toml
- uvm_core/src/error.rs
- uvm_core/src/lib.rs
- uvm_core/src/unity/current_installation.rs
- uvm_core/src/unity/installation.rs
- uvm_core/src/unity/mod.rs
Read macOS type of unity installation. This first strategy will only work on mac os machines.
> Refactor unity installation recognision logic

- uvm_cli/src/lib.rs
The function `pub fn exec_command<C, I, S>(command: C, args: I) -> io::Result<i32>` is used to call a child process (in most cases a sub command) and run it. As of now this meant that the mother process `uvm` was still executing. I replaces `spawn` with the system depending function `exec`. It is save to call `exec` here because both usecases of `exec_command` just gather resources to hand them over to the child process. …
> Replace `spawn` method with `exec` in exec_command function

- uvm_core/Cargo.toml
- uvm_core/src/lib.rs
- uvm_core/src/unity/version/mod.rs
Use crate [semver] as the base version component instead of defining `major`, `minor` and `patch` on our own. This moves some of the version comparision down to the [semver] implementation.
This refactor also adds some helper methods to create versions.
* `a()` create a alpha version
* `b()` create a beta version
* `p()` create a patch version
* `f()` create a final version
and a `From<(u64,u64,u64,u64)>` implementation.
[semver]: https://crates.io/crates/semver …
> Refactor unity::Version

- uvm_core/Cargo.toml
- uvm_core/src/install/installer/windows.rs
- uvm_core/src/lib.rs
The windows unity installer accepts a commandline flag `/D` to set the destination for the installation. This flag must be provided in the form `/D=some\destination`. The rust `std::process::Command::spawn` method does some things to the provides arguments so that the installer skips over the flag. The result is that the installer uses the last selected destination and writes over the possible installation. This patch fixes this problem with a temp solution. I couldn't find a incantation from rust that worked so the patch logic introduces a tempary batch file with the correct installer incatation.
[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg …
> Fix windows installer logic

- .travis.yml
- install/uvm-install2/Cargo.toml
- install/uvm-install2/src/lib.rs
- uvm_core/Cargo.toml
- uvm_core/src/install/mod.rs
- uvm_core/src/lib.rs
- uvm_core/src/unity/component.rs
- uvm_core/src/unity/hub/paths.rs
- uvm_core/src/unity/mod.rs
- uvm_core/src/unity/version/manifest/mod.rs
- uvm_core/src/unity/version/mod.rs
- uvm_core/src/utils.rs
- uvm_core/tests/download_unity_installer.rs
The first implementation used `brew cask` to download the unity module installers. This implementation doesn't work on windows or linux so this patch adds a first implementation for a custom download logic. The installer locations are fetched from the version manifest and downloaded to a `cache` directory:
* macos: `~/Library/Caches/Wooga/UnityVersionManager/installers`
* windows : `%HOME%/AppData/Local/UnityVersionManager/installers`
The download process is restartable if the tool fails or any other interrupt happens. The install command and the download function will create a lock file to lock the temporary installation file so that only one uvm process can access it at the same time.
All installer binaries are verified with the provided `md5` checksum from the unity version manifest. …
> Add custom install downloader

- uvm_cli/Cargo.toml
- uvm_cli/src/lib.rs
The underlying cli options trait has been moved to a new crate [cli_core]. This crate is also used for another `uvm` related project and doesn't need the `uvm_core` dependencies.
[cli_core]: https://crates.io/crates/cli_core
[BREAK]:http://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg "Remove" …
> Move some cli base traits/function to custom crate

- uvm_core/src/unity/urls.rs
- uvm_core/src/unity/version/manifest/mod.rs
This patch is a small cleanup to use the `Deref` trait instead of defining delegate functions for the `Url` wrapper structs `DownloadURL` and `IniUrl`. These structs also implement the `Into<Url>` trait to convert them into Url objects.
[BREAK]:http://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg "Remove" …
> Use Deref trait for Url tuple structs

- uvm_core/src/install/installer/windows.rs
- uvm_core/src/unity/component.rs
Windows installers only need the path to the directory which contains the `Unity.exe`. But to check if a specific component is installed we need also the complete path to the installation location. This patch adds a another function to `Component` to fetch either the installer path or the installation location. On macOS both paths are equal. …
> Fix component install path and install location check

- install/uvm-versions/src/lib.rs
- install/uvm-versions/src/main.rs
To list only versions of interest, the `versions` command now understands an optional argument `pattern`. The pattern is a regex string and will be matched on the result list
after filtering the release types etc.
_all versions containing `1`_
```
$uvm versions 1
Latest versions to install matching the pattern `1`:
2018.2.14f1
2018.3.0b8
5.6.4p1
5.6.4f1
2019.1.0a7
2017.3.1p4
2017.4.14f1
2017.3.0b11
```
_all versions starting with `2`_
```
$uvm versions ^2
Latest versions to install matching the pattern `^2`:
2017.4.14f1
2017.3.0b11
2017.3.1p4
2018.3.0b8
2018.2.14f1
2019.1.0a7
```
_all versions starting with `2` and end with `4`_
```
$uvm versions '^2.*4$'
Latest versions to install matching the pattern `^2.*4$`:
2017.3.1p4
```
_all versions starting with `2017` or `2019`_
```
$uvm …
```
> Add optional pattern argument to versions command

- uvm_core/src/unity/hub/paths.rs
- uvm_core/src/unity/urls.rs
- uvm_core/src/unity/version/hash.rs
- uvm_core/src/unity/version/mod.rs
Instead of using a static list of released versions, we should use a remote service to fetch a recent list of released unity versions. This patch adds a remote call to the [unity-versions-service] to fetch a complete list of all available versions to install and to fetch the revision hash for a given version to create the manifest url.
The function `uvm_core::unity::version::hash::all_versions` used to create an iterator from a `HashMap` created at runtime from a static yml string. This `HashMap` is still in place for now for the revision hash fetch but no longer used for the list of all available versions. The new implementation will call a remove service [unity-versions-service] with the endpoint `/versions` to retrieve an up-to-date list of all versions. There is no local cache or …
> Use unity-versions-service for version lookup

- install/uvm-versions/Cargo.toml
- install/uvm-versions/src/lib.rs
- install/uvm-versions/src/main.rs
- uvm_core/src/unity/version/mod.rs
The whole version filter logic in the `uvm versions` command is quite complicated and a long mess. This patch tries to add more readability by splitting the logic into multiple functions. Instead of long type names for nested `HashMap`s this patch adds some internal type aliases. This keeps the function definitions shorter and adds more clarity.
This won't be the last time this command is refactored because
readability is only partially created with these changes. …
> Cleanup versions command

- install/uvm-install/src/lib.rs
This patch is a additional patch for https://github.com/Larusso/unity-version-manager/pull/36
The last patch missed the duplicate code in case we want to install a
component for a already installed unity version.
* ![FIX] windows component install when version is already installed
[BREAK]:http://resources.atlas.wooga.com/icons/icon_break.svg "Remove" …
> Fix windows component install when version is already installed

- uvm_core/src/unity/installation.rs
The helper method `adjust_path` that checks if the proved path to a unity installation is pointing to a Unity executable adjusted the path incorrect. In windows the path to the executable inside of an
installation is as follows:
`installation_dir\Editor\Unity.exe`
We need to get the parent of the `Editor` directory. The incorrect implementation did one `parent` to much.
* ![FIX] `adjust_path` implementation for windows
> Fix adjust_path for installation on windows OS

- .travis.yml
- Cargo.lock
- Cross.toml
- README.md
- ci/custom_images/x86_64-unknown-linux-gnu.Dockerfile
- install/uvm-install/src/lib.rs
- uvm_core/Cargo.toml
- uvm_core/src/install/installer/linux.rs
- uvm_core/src/install/installer/macos.rs
- uvm_core/src/install/installer/mod.rs
- uvm_core/src/lib.rs
- uvm_core/src/unity/component.rs
- uvm_core/src/unity/hub/editors/mod.rs
- uvm_core/src/unity/hub/paths.rs
- uvm_core/src/unity/installation.rs
- uvm_core/src/unity/mod.rs
- uvm_core/src/unity/urls.rs
- uvm_core/src/unity/version/linux.rs
- uvm_core/src/unity/version/manifest/mod.rs
- uvm_core/src/unity/version/mod.rs
- uvm_core/src/unity/version/other.rs
This patch adds expirimtal support for the linux platform. It contains a new installation routine for linux to install Unity editor versions and components. As of this point not all Editor versions are available. This needs to be verified and maybe the versions endpoint should be updated to reflect that.
The linux default installation, config and cache paths follow the paths configured in UnityHub
installation location: `$HOME/Unity/Hub/Editor/`
config location: `($XDG_CONFIG_HOME|$HOME/.config)/UnityHub`
cache location: `($XDG_CACHE_HOME|$HOME/.config)/Wooga/UnityVersionManager`
* ![ADD] Linux support
> Linux Support

- uvm_core/src/install/installer/loader.rs
- uvm_core/src/unity/version/manifest/de.rs
- uvm_core/src/unity/version/manifest/mod.rs
Description
===========
A small refactoring for `unity::version::Manifest`. The version field `unity::Version` in this struct is now a reference. The manifest gets created with this version and doesn't need to own it. This patch also adds smaller additions for the contained structs in the `manifest.rs` file and some code reorderings.
The `ComponentData` struct contains a new field `download_url` which gets created after de-serializing the manifest ini file. This allows to fetch the download url of a component without having a reference to the manifest itself.
As a small cleanup I created a custom serde module in `de.rs` with
functions to deserialize `bool` values in ini files.
Changes
=======
* ![IMPROVE] `unity::version::Manifest`
* ![ADD] ![NEW] field `download_url` to `ComponentData`
* …
> Improve unity::version::Manifest

- Cargo.lock
- uvm_core/Cargo.toml
- uvm_core/src/unity/version/manifest/mod.rs
The current API of `unity::version::Manifest` allows only to load a manifest file with a specified version from the internet. If the manifest in question was cached the cached version was returned. This patch adds new API's to create `unity::version::Manifest` structs from `Read` or `Path`. Because of the internal structure of Manifest and the problem that a manifest has no idea about it's own version we need to parse the version before we can parse the rest of the file. This might be worth another refactor.
* ![ADD] `read_manifest_version_from_path` in `unity::version::Manifest`
* ![ADD] `read_manifest_version` in `unity::version::Manifest`
* ![ADD] `from_reader` in `unity::version::Manifest`
* ![ADD] `new` in `unity::version::Manifest` …
> Add new API methods to create manifest from reader path

- Cargo.lock
- commands/uvm-download-manifest/Cargo.toml
- commands/uvm-download-manifest/src/lib.rs
- commands/uvm-download-manifest/src/main.rs
- unity-2017.4.30f1-osx.ini
- uvm_core/src/lib.rs
- uvm_core/src/platform.rs
- uvm_core/src/unity/urls.rs
For testing purposes I created a small helper command to download a unity manifest by version and platform. I don't know how long this command will be here to stay and I don't see it as part of the API.
To configure the platform parameter on the `IniUrl` I created a new builder struct. By default the current system platform will be used. Before this was done with compile time checks. This has moved into the default implementation of the new enum `Platform`. The `IniUrlBuilder` can be used to set a different platform than the current system
platform. …
> Add auxiliary command download-manifest

- commands/uvm-generate-modules-json/tests/fixures/linux/v2019/2019.3.0a8_modules.json
- commands/uvm-generate-modules-json/tests/fixures/mac/v2019/2019.3.0a8_modules.json
- commands/uvm-generate-modules-json/tests/fixures/win/v2019/2019.3.0a8_modules.json
- uvm_core/src/sys/linux/unity/version/module.rs
- uvm_core/src/sys/mac/unity/version/module.rs
- uvm_core/src/sys/win/unity/version/module.rs
I picked `r19b` for the ndk version because this was what the https://public-cdn.cloud.unity3d.com/hub/prod/releases-darwin.json file told me at one point. This seems to be an error since Unity complains about this version. This fix simply reverts to `r19`.
> Fix ndk version for unity 2019.3

- commands/uvm-generate-modules-json/tests/fixures/mac/v2019/2019.3.0a8_modules.json
- uvm_core/src/sys/mac/unity/component.rs
- uvm_core/src/sys/win/unity/component.rs
During development I saw a discrepancy with the `linux-mono` installation path reported by Unity Hub on macOS. Normally all Unity published components use installers that exactly know where it should be installed into. The official `modules.json` states `$UNITY_PATH` for this new module. I tried installing it via Unity Hub and found and it didn't work. After moving the installed items into `PlaybackEngines\LinuxStandaloneSupport` I was able to use the component from within Unity. I opened a [bug report] to make Unity aware of this issue.
Since I'm fairly certain that this is a bug and keeping a reference implantation with Unity Hub would result in non working installation I decided to update my `modules.json` generator logic and patch it right away.
[bug report]: …
> Fix linux-mono component installation path

- Cargo.lock
- commands/uvm-fix-modules-json/Cargo.toml
- commands/uvm-fix-modules-json/src/lib.rs
- commands/uvm-fix-modules-json/src/main.rs
- commands/uvm-generate-modules-json/src/lib.rs
- commands/uvm-generate-modules-json/src/main.rs
- uvm_core/src/unity/component/mod.rs
- uvm_core/src/unity/mod.rs
- uvm_core/src/unity/version/module.rs
The first version of the command missed the desired usage. So I split the command into two.
- `generate-modules-json`
- `fix-modules-json`
The use case for the `fix-modules-json` command is the actual initial idea for the `generate-modules-json` command which got lost during implementation. This new command reads the given version to generate/update the `modules.json` file for. In contrast to the original implementation, it marks modules in the file as selected when they are installed.
The `generate-modules-json` command was changed to mimic the behavior of `download-manifest`. It is possible to generate a `modules.json` file for any valid Unity version. The term `generate` is important as this file is still created at runtime and not fetched from any remote or local location.
addresses: …
> Fix generate modules json command

- Cargo.lock
- Makefile
- install/uvm-modules/Cargo.toml
- install/uvm-modules/src/lib.rs
- install/uvm-modules/src/main.rs
- uvm_core/src/unity/component/category.rs
- uvm_core/src/unity/component/error.rs
- uvm_core/src/unity/component/mod.rs
- uvm_core/src/unity/mod.rs
- uvm_core/src/unity/version/module.rs
As a preparation for changes in the command line interface of the install command, I added this new helper command `uvm-modules` which lists available modules for the given versions.
```
uvm-modules - List available modules for a specified unity version.
Usage:
uvm-modules [options] [--category=CATEGORY...] <version>
uvm-modules (-h | --help)
Options:
-c=CATEGORY, --category=CATEGORY    filter by category
-v, --verbose                       print more output
-d, --debug                         print debug output
--color WHEN                        Coloring: auto, always, never [default: auto]
-h, --help                          show this help message and exit
Arguments:
<version>              The unity version to list modules for in the form of `2018.1.0f3`
```
The command is quite slow …
> Add uvm-modules command

- uvm_core/src/unity/component/mod.rs
- uvm_core/src/unity/version/module.rs
The internal data structures got a little bit shaken when introducing the support of the Unity Hub modules. The future plan is to use the `Module` struct as the single point of truth and only rely on the ini Manifests when needed. The `Module` struct is in some way a superset of the `Manifest` hash map but is implemented in a way that makes some hard choices when reading and comparing between the two. One issue early on was the `id` field of the `Module`. This field is actually a different `string` representation of `Component` I choose not to use the `Component` enum directly in the beginning concentrate on the actual generator code. The `Component` enum is serialize able with `serde` but all field annoation match the names and settings for the `Manifest` ini representation. So I left it …
> Improve unity::Module struct by using unity::Component as id

- Cargo.lock
- uvm_core/Cargo.toml
- uvm_core/src/utils.rs
This patch updates [`cluFlock`] to `1.2.5`. From `0.1.5` it got quite some internal changes. It is compatible with windows now which means a future patch can remove the helper functions and macros I created and use it as described in `cluFlock` documentation examples.
resolves #59 
[`cluFlock`]: https://crates.io/crates/cluFlock
> Update cluFlock to latest version 1.2.5

- uvm_core/src/unity/component/mod.rs
- uvm_core/src/unity/version/module.rs
To make it esier in the future to map and connect different modules which are linked with the `parent` or `sync` field, we need to use the same types for module `id`, `sync` and `parent`. This patch does this in a crude way. I had some problems getting `serde` to emit the correct code so that I can also serialize/deserialize `Option<Component>` types.
One noteworthy point is the fact that Unity serializes the `android` component as `Android Build Support`, but only for the `sync` field. I kept this error because I have no idea at the moment if Unity Hub works if the value would be encoded correctly with `android`.
> Improve module struct layout

- install/uvm-modules/src/lib.rs
- install/uvm-modules/src/main.rs
This patch improves the output for the `modules` command. Instead of
hiding all `sync` and `hidden` modules, it adds option flags to list
those as well. I had to introduce a hacky wrapper struct to create the
tree like output for the `sync` modules. I want to incorparate this in
the core crate when I have a better idea how to parse and layout this
modules.
```
uvm-modules - List available modules for a specified unity version.
Usage:
uvm-modules [options] [--category=CATEGORY...] <version>
uvm-modules (-h | --help)
Options:
-c=CATEGORY, --category=CATEGORY    filter by category
-s, --show-sync-modules             list also sync modules
-a, --all                           list also invisible modules
-v, --verbose                       print more output
-d, --debug …
```
> Improve modules listing

- Cargo.lock
- install/uvm-install-module/Cargo.toml
- install/uvm-install-module/src/lib.rs
- install/uvm-install-module/src/main.rs
- uvm_core/Cargo.toml
- uvm_core/src/sys/mac/installer.rs
This is the first patch in a series to improve the module installation support on all system and reach Unity Hub parity. This patch concentrates on the macOS platform. It adds three new installer type supports
* zip
* po
* dmg
On the macOS platform most modules are installed with `pkg` packages. The only exceptions are the new external android build tools packages. These are all configured as `zip` archives. The current implementation extracts the content of the requested archives to a chooses destination directory. The module description contains two new fields `renameFrom` and `renameTwo`. These final operations are not part of this patch because the install function has no context knowledge about the module to be installed.
`*.po` files are translation files which get installed …
> Improve macos module installer support

- uvm_core/src/sys/linux/installer.rs
- uvm_core/src/sys/mac/installer.rs
- uvm_core/src/sys/mod.rs
- uvm_core/src/sys/shared/installer.rs
- uvm_core/src/sys/shared/mod.rs
Second patch to gain Unity Hub parity for module installation. Linux had already all nessary installer types covered. This patch concentrates more on cleanup and code sharing. I moved a few functions with the same logic into a `shared` module just to reduce overhead. I also retouched the general logic in the `_install_module` function to make it similar to the macOS variant.
[LINUX]:https://atlas-resources.wooga.com/icons/icon_linux.svg "Linux"
> Improve linux module installer

- Cargo.lock
- uvm_core/Cargo.toml
- uvm_core/src/lib.rs
- uvm_core/src/sys/shared/installer.rs
After some additional testing with the new installer logic I realized that some modules where not working inside of Unity. Most prominently is the `OpenJDK` module which stopped working for me after an update to the latest `2019.3` beta. The reason was that Unity shipped the JDK twice and never actually used the JDK installed as a zip package but the one contained in the base android module which is shipped as a `pkg` package. The issue boils down to the fact that the `unzip` library isn't setting the UNIX permissions after extracting the files from the archive. Android SDK tools missed the executable permission and where unusable. This patch replaces the [`unzip`] crate with [`zip`]. The whole extract logic is converted from the example in the [`zip`] repository.
A second smaller fix was …
> Fix zip module installer

- Cargo.lock
- uvm_core/Cargo.toml
- uvm_core/src/lib.rs
- uvm_core/src/sys/linux/unity/version/module.rs
- uvm_core/src/sys/mac/unity/version/module.rs
- uvm_core/src/sys/shared/installer.rs
- uvm_core/src/sys/win/unity/version/module.rs
- uvm_core/src/unity/version/module.rs
This patch makes handling of file paths from modules easier. Instead of serializing these values to `String` objects we use `std::path::PathBuf` instead.
* ![IMPROVE] module destination fields as `std::path::PathBuf`
> Improve module destination fields as std::path::PathBuf

- install/uvm-install/src/lib.rs
- uvm_core/src/install/installer/loader.rs
- uvm_core/src/install/mod.rs
- uvm_core/src/unity/mod.rs
- uvm_core/src/unity/version/manifest/v2/mod.rs
Description
===========
For the new planned installer I need to slightly refactor the `uvm_core::installer::Loader` struct and adjust it's API. The plan to remove `install::Variant` in the long run and replace it directly with `uvm_core::unity::Component`. The `new` method is changed to accept any type which implements `Into<Component>`. I also realized that each loader instance loads its own copy of the manifest. This is unnecessary. Instead the loader is now constructed with a manifest ref instead. I changed the `download_installer` helper method to limit the API breakage.
Changes
=======
* ![CHANGE] `uvm_core::installer::Loader` API
* ![IMPROVE] loader manifest loading …
> Refactor Loader

- Cargo.lock
- Cargo.toml
- uvm_install_graph/Cargo.toml
- uvm_install_graph/README.md
- uvm_install_graph/src/lib.rs
- uvm_install_graph/tests/fixures/linux/2019.3.0a8_manifest.ini
- uvm_install_graph/tests/fixures/linux/mod.rs
- uvm_install_graph/tests/fixures/mac/2019.3.0a8_manifest.ini
- uvm_install_graph/tests/fixures/mac/mod.rs
- uvm_install_graph/tests/fixures/mod.rs
- uvm_install_graph/tests/fixures/win/2019.3.0a8_manifest.ini
- uvm_install_graph/tests/fixures/win/mod.rs
- uvm_install_graph/tests/graph_tests.rs
This patch adds a new helper crate `uvm_install_graph`. A simple [directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) representation of a unity version and it's modules. This graph allows the traversal of to be installed modules in a topological order.
It is also possible to query submodule and or dependencies for a given module. This graph will be used by the new installer to walk the version manifest in topological order and install missing/requested modules.
* ![ADD] ![NEW] `uvm_install_graph` crate
> Add uvm_install_graph crate

- uvm_core/src/install/installer/loader.rs
- uvm_core/src/utils.rs
Some of the new module packages contain installer urls without filename parts. For these urls the tool needs to make some additional calls to said url to retrieve the final name. This patch fix implements a fix with the help of a new utility method.
The new function `uvm_core::utils::UrlUtils::get_file_name_from_url` will check if the provided url ends with a filename. If yes this filename will be returned otherwise execute a `HEAD` call and try to read the `content-disposition` header. If this fails try to read the name from the redirection url.
* ![FIX] missing installer filename
* ![ADD] `UrlUtils` struct with `get_file_name_from_url` function …
> Fix missing installer filename

- install/uvm-install-editor/src/lib.rs
- install/uvm-install-module/src/lib.rs
- install/uvm-install/src/lib.rs
- uvm_core/src/sys/linux/installer.rs
- uvm_core/src/sys/mac/installer.rs
- uvm_core/src/sys/win/installer.rs
To support all new and old support modules I need to adjust the installer API. At the moment each module installation required a destination path for the installation. Sadly some modules only have no destination configured and either use a default value or none at all. That is a problem because validating which default value to use is platform and installer type specific. Which means that this can only be handled in the installer directly. I made the decision to change the API for `install_editor` and `install_module` to support an `Option<AsRef<Path>>` value. The installer will valid the destination and fail if a destination is required but not passed down.
* ![CHANGE] installer API …
> Refactor installer API

- commands/uvm-generate-modules-json/tests/fixures/win/v2019/2019.3.0a8_modules.json
- uvm_core/src/unity/version/module.rs
The `uvm_core::unity::Module` struct is missing the `cmd` property mainly used in windows. The `cmd` property from the ini files get converted once more before assigned to the module instances.
* ![FIX] missing `cmd` property in `uvm_core::unity::Module`
* ![FIX] module generator test fixums
* ![FIX] windows path serialization 
> Fix missing cmd property in modules

- Cargo.lock
- install/uvm-install-editor/src/lib.rs
- install/uvm-install-module/src/lib.rs
- install/uvm-install/src/lib.rs
- uvm_core/Cargo.toml
- uvm_core/src/sys/win/installer.rs
Third patch to gain Unity Hub parity for module installation. For windows it was necessary to implement other changes first to get to the point to safely implement the missing installer types.
This patch adds the missing installer types:
* zip
* po
* msi
Zip is used as for all other platforms. It invokes the shared cross platform implementation.
The `msi` installer is tricky. It seems to be used only by `Facebook Gameroom`. It seems Unity Hub expects a specigic `cmd` string to replace the installer path. I use the same trick as used with the `exe` installers by creating a temp `cmd` script which invokes the installer comand. At one point it might be worth investigating in a `CommandExt` to call the windows process in the correct way.
Changes
======= …
> Improve windows module installer support

- Cargo.toml
- uvm_move_dir/Cargo.toml
- uvm_move_dir/README.md
- uvm_move_dir/src/lib.rs
- uvm_move_dir/src/win_move_file.rs
- uvm_move_dir/tests/helper/mod.rs
- uvm_move_dir/tests/move_dir_inner_tests.rs
- uvm_move_dir/tests/rename_dir_tests.rs
`uvm_move_dir` contains opinionated directory move operations. Some of the new module installation processes require to move a directory into itself (e.g. `/foo/bar/baz` `->` `/foo/bar`). Most crates and even the std functions don't allow this. This crate tries to solve this in a non generic way. These methods are only intended for the specific use-case. A custom windows call is also provided to provide the same behavior as `std::fs::rename` when providing directories as `from` and `to`. …
> Add uvm_move_dir

- uvm_move_dir/src/lib.rs
- uvm_move_dir/tests/rename_dir_tests.rs
This patch adds some input checks to fail early when source and destination paths are not directories.
* ![IMPROVE] `uvm_move_dir` input validation
> Improve uvm_move_dir input validation

- commands/uvm-fix-modules-json/Cargo.toml
- commands/uvm-fix-modules-json/src/main.rs
- commands/uvm-generate-modules-json/src/main.rs
- uvm_core/src/unity/version/manifest/v2/mod.rs
- uvm_core/src/utils.rs
This patch adds two new function to the `Manifest` struct.
* `modules_json`
* `write_modules_json`
Both functions convert the internal modules list to json. These two functions allow to create/write the `modules.json` file with a borrowed manifest without converting it to a `Vec<Module>`. Both commands that write the `modules.json` are also updated.
* ![ADD] function `modules_json` to `Manifest`
* ![ADD] function `write_modules_json` to `Manifest`
* ![IMPROVE] `uvm-fix-modules-json` command,use `write_modules_json`
* ![IMPROVE] `uvm-generate-modules-json` command, use `write_modules_json`
[IMPROVE]:https://atlas-resources.wooga.com/icons/icon_improve.svg …
> Add write_modules_json function to Manifest

- uvm_move_dir/src/lib.rs
- uvm_move_dir/tests/move_dir_up_tests.rs
The crate `uvm_move_dir` is missing a move use case.
source = `/path/to/dir`
destination = `/path/to/new/dir`
This patch adds the missing functionality for both Unix and windows.
[REMOVE]:https://atlas-resources.wooga.com/icons/icon_remove.svg "Remove" …
> Fix missing move usecase

- commands/uvm-generate-modules-json/tests/fixures/win/v2019/2019.1.10f1_modules.json
- commands/uvm-generate-modules-json/tests/fixures/win/v2019/2019.2.0b9_modules.json
- commands/uvm-generate-modules-json/tests/fixures/win/v2019/2019.3.0a8_modules.json
- uvm_core/src/sys/linux/unity/component.rs
- uvm_core/src/sys/mac/unity/component.rs
- uvm_core/src/sys/win/unity/component.rs
I realized that some of the installpath and install_location returns were incorrect when compared to the offical `modules.json` files coming from Unity.
Example:
_macOS android-sdk-build-tools_
```json
"destination": "{UNITY_PATH}/PlaybackEngines/AndroidPlayer/SDK/build-tools",
"renameTo": "{UNITY_PATH}/PlaybackEngines/AndroidPlayer/SDK/build-tools/28.0.3",
"renameFrom": "{UNITY_PATH}/PlaybackEngines/AndroidPlayer/SDK/build-tools/android-9"
```
_windows android-sdk-build-tools_
```json
"destination": "{UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer/SDK",
"renameTo": "{UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platforms/android-28",
"renameFrom": "{UNITY_PATH}/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/android-9"
```
The difference is marginal and yields a similar …
> Fix modules install path

- uvm_core/src/sys/win/installer.rs
- uvm_core/src/utils.rs
Description
============
To activate support for long path names I added a utility function which can be used to prepend a given path with a specific opt in prefix `\\?\` From the windows [docs][0]:
> For file I/O, the "\\?\" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system. For example, if the file system supports large paths and file names, you can exceed the MAX_PATH limits that are otherwise enforced by the Windows APIs. For more information about the normal maximum path limitation, see the previous section Maximum Path Length Limitation.
More info can be found [here][0]
The windows installer functions call this new utility function and prefix all destination urls.
Changes
=======
* ![ADD] …
> Add windows long path support function

- uvm_core/src/unity/component/mod.rs
- uvm_core/src/unity/version/module.rs
A simple patch that adds `AsRef<Component>` implementations for both `uvm_core::unity::Component` and `uvm_core::unity::Module`.
* ![ADD] `AsRef<Component>` impl for `uvm_core::unity::Component`
* ![ADD] `AsRef<Component>` impl for `uvm_core::unity::Module` …
> Add AsRef<Component> iml for Component and Module

- .travis.yml
- Cargo.lock
- ci/script.sh
- install/uvm-install2/Cargo.toml
- install/uvm-install2/src/error.rs
- install/uvm-install2/src/lib.rs
- install/uvm-install2/src/main.rs
- install/uvm-install2/tests/install_tests.rs
This patch brings in a complete new installer. It's a first step for an installer that manages to be fully compatible with all unity module types. The command line interface is very different compared to the original `uvm-install` command. Modules have to be references by `id` instead of commandline flags. It becomes impossible to keep a list of possible flags when each version of unity changes names/numbers of modules. The helper task `uvm-modules` should be used to fetch a list of available modules for a given unity version.
```
USAGE:
uvm-install2 [FLAGS] [OPTIONS] <version> [--] [destination]
FLAGS:
-d, --debug
print debug output
-h, --help
Prints help information
--with-sync
install also synced modules
-V, --version
Prints version information
-v, --verbose
print more output
OPTIONS: …
```
> Add new install command uvm_install2

- install/uvm-install2/src/lib.rs
- install/uvm-install2/tests/install_tests.rs
Whenever a installation destination is set to a custom directory, the installer should add the installation to the unity hub editors list. The old installer did this. I added the missing lines of code and updated the tests.
* ![FIX] add installation to unity hub editors list …
> Fix add installation to unity hub editors list

- install/uvm-install2/src/lib.rs
The move operation of certain modules can fail if the path is longer  than `PATH_MAX`. This patch adds the long path prefix on windows before executing the move.
* ![FIX] prepend windows long path
[REMOVE]:https://atlas-resources.wooga.com/icons/icon_remove.svg "Remove" …
> Fix prepend windows long path during module move

- Cargo.lock
- uvm_move_dir/Cargo.toml
- uvm_move_dir/src/lib.rs
This is a desperate attempt to mitigate issues when both source anddestination are on different volumes than the default temp location. This issue should be fixed by copying files rather rename directories twice. On windows this could be handled with an option flag. …
> Fix try to create temp dir on same disk volume

- .travis.yml
The `i686-apple-darwin` is no longer a first tier support target and is
no longer needed.
> Remove i686-apple-darwin build target

- install/uvm-install2/Cargo.toml
- install/uvm-install2/src/lib.rs
The `install2` command was not locking the install process for the given version like the old implementation does. That results in some buggy behavior when two processes of uvm install2 try to install or alter the same unity installation.
The patch simply locks the whole install method if another process is trying to alter the Unity installation for a given version. This means even parallel calls of `install` and `install2` should be covered.
* ![FIX] missing install process lock for `install2` command
[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:      https://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:  https://resources.atlas.wooga.com/icons/icon_improve.svg "Improve"
[CHANGE]:   https://resources.atlas.wooga.com/icons/icon_change.svg …
> Fix missing install process lock for install2 command

- Cargo.lock
- commands/uvm-list/Cargo.toml
- commands/uvm-list/src/main.rs
##Description
The `uvm-list` command used to print the default uvm installations as a default. These are installations from the default system installation location.
windows: `c:\program files\`
macOS: `/Applications`
linux: `$HOME/.local/bin`
This makes no real sense as a default since uvm installs by default to the unity hub configured locations. So the default listing is now the `--hub` listing.
> Improve uvm-list command defaults listing

- install/uvm-install2/src/error.rs
- install/uvm-install2/src/lib.rs
The install2 `install` function panics when one or more modules are selected, which are not compatible with the selected unity version to install. The component enum values are not save to use over all versions of unity. This can only be determined at runtime. The old implementation did a simple unwrap and panicked. I rewrote the logic to yield a `Result<HashSet<Component>>` instead.
> Fix unwrap panic during install with unsupported modules

- commands/uvm-detect/src/main.rs
- commands/uvm-fix-modules-json/src/main.rs
- commands/uvm-help/src/main.rs
- commands/uvm-launch/src/main.rs
- commands/uvm-list/src/main.rs
- commands/uvm-version/src/main.rs
- install/uvm-install2/src/main.rs
- install/uvm-modules/src/main.rs
- install/uvm-versions/src/main.rs
This patch fixes a small output bug. When calling the help page, the command would
print an error message which comes from the default rust implementation when main returns an error result. This patch simply calls the failing method of `structopt` `from_args` which will panic.
It also enables color output for the cli help.
> Fix error print in --help messages.

- install/uvm_install_core/src/sys/linux/xz.rs
The `iOSSupport` module is the only package on `macOS` which is archived based on a different base directory than all other packages. This is sadly also true for the linux version of the module. So I adjusted the installation destination when the package destination contains `iOSSupport` in the path.
> Fix iOSSupport module installation destination on linux

- commands/uvm-list/src/main.rs
Adds a new commandline option `--modules` or `-m` to print list of installed modules for each installed Unity version.
```
Installed Unity versions:
2020.3.29f1
standardassets
example
android
ios
linux
linux-mono
linux-il2cpp
linux-server
2019.4.24f1
standardassets
example
android
android-sdk-build-tools
android-sdk-platforms
android-sdk-platform-tools
android-sdk-ndk-tools
android-ndk
android-open-jdk
ios
linux
linux-mono
linux-il2cpp
linux-server
webgl
```
> Add option to to list installed modules to umv-list command

- Cargo.lock
- uvm_core/Cargo.toml
- uvm_core/src/error.rs
- uvm_core/src/sys/linux/unity/version/mod.rs
- uvm_core/src/sys/mac/unity/version/mod.rs
- uvm_core/src/sys/win/unity/version/mod.rs
- uvm_core/src/unity/mod.rs
- uvm_core/src/unity/version/error.rs
- uvm_core/src/unity/version/mod.rs
The unity version module already had a custom error implementation based on the `error-chain` cask.
I reimplemented the error based on `thiserror` and cleaned up some cases. I'm not 100% happy about the result but would revisit this again at a later stage. I'm not super fond of the introduction of anyhow as a catch all item.f
> Improve error handling Patch II

- uvm_core/src/unity/component/category.rs
- uvm_core/src/unity/component/error.rs
- uvm_core/src/unity/component/mod.rs
- uvm_core/src/unity/localization.rs
- uvm_core/src/unity/mod.rs
Third patch to move from `error_chain` to `thiserror`. In this patch I take care of the `uvm_core::unity::Component` parsing errors for both `Component` and the inner `Localization` enum.
> Improve error handling Patch III

- uvm_core/src/error.rs
- uvm_core/src/platform.rs
- uvm_core/src/unity/hub/editors/mod.rs
- uvm_core/src/unity/hub/mod.rs
This patch converts the `UvmHubError` from `error_chain` to `thiserror` backed errors. I already see that I need another general rename patch to clean things up for good after I setup all the different error cases/enums etc.
> Improve error handling Patch IV

- uvm_core/src/unity/version/hash.rs
- uvm_core/src/unity/version/mod.rs
Unity versions always come with two components:
* The actual version string
* a hash part which is mostly invisible
To install and locate the install resources we need both parts. In the past a webservice was used to locate the missing hash by providing a simple mapping. Since Unity 2019 the project settings file declares the project version in two styles:
```
m_EditorVersion: 2020.3.38f1
m_EditorVersionWithRevision: 2020.3.38f1 (8f5fde82e2dc)
```
The newer `m_EditorVersionWithRevision` version already contains the hash/revision (unity itself is not clear how to name this ...) I updated the version `fromString` parser to parse the optional revision when provided. I opted to parse 2 styles. the aformentioned project settings style and also the UnityHub url style `2020.3.38f1/8f5fde82e2dc`.
> Improve unity version parsing

- install/uvm-install/src/error.rs
- install/uvm-install/src/lib.rs
- install/uvm-install2/src/error.rs
- install/uvm-install2/src/lib.rs
- install/uvm_install_core/src/error.rs
- install/uvm_install_core/src/loader.rs
- uvm_core/src/unity/hub/paths.rs
- uvm_core/src/unity/version/manifest/ini.rs
- uvm_core/src/unity/version/mod.rs
The installer cache worked fine and has functionally no issues. The reason I was compelled to patch it is that Unity sometimes creates internal fix releases with a different revision hash. This means that when the actual fix gets rolled out, uvm might think that the installer for the version is already downloaded.
This is a very simple patch to make sure that we use both user version + revision hash as the cache key for the installer and lock files.
While touching it I moved the cache folder to a new home. I use the github domain for the cache dir instead of `Wooga/UnityVersionManager`. I also decided to keep the temp download files in a seperate directory.
> Improve install cache

- uvm_core/src/sys/linux/unity/component.rs
The `LinuxMono` unity component is listed as one of the default 'built-in' linux components. While unity work as the linux-mono component is already installed, this generates an inconsistency with other OSes that doesn't list their [os]-mono packages, which behave in the same way. 
This PR removes the LinuxMono from the list built-in linux components to keep consistency.
> Remove LinuxMono from list of Unity built-in components

- .graphqlconfig
- Cargo.lock
- Cargo.toml
- commands/uvm-generate-versions-yaml/Cargo.toml
- commands/uvm-generate-versions-yaml/src/cli.rs
- commands/uvm-generate-versions-yaml/src/main.rs
- uvm_live_platform/Cargo.toml
- uvm_live_platform/schema.graphql
- uvm_live_platform/src/api/list_versions.rs
- uvm_live_platform/src/api/list_versions_query.graphql
- uvm_live_platform/src/api/mod.rs
- uvm_live_platform/src/error.rs
- uvm_live_platform/src/lib.rs
- uvm_live_platform/src/model.rs
This is a first patch to introduce a new crate to connect to the live platform service. This service is a graphql service which allows a handful of operations around unity releases etc. This service is used directly by UnityHub to query latest releases and to fetch information for older releases. This used to be semi-hardcoded in Unity Hub. The first API allows to query for Unity versions. Others will follow soon.
> Add new crate to connect to unity live platform service

- install/uvm_install_core/src/sys/linux/pkg.rs
It seems a very old bug suddenly surfaced.
The linux pkg install logic is reading the contents of the archive into memory and passing it down to the stdin for the `cpio` command. I used the singe `write` call to copy the `buffer` to the `stdin` without checking if all bytes are actually written. It seems pure luck that this worked until now. It seems that in recent versions of Unity some packages got so big that a single call to `write` wasn't writing all the bytes into the memory location.
I replaced the logic with a filestream copy instead. Something I should have done to begin with ...
> Fix linux installation for newer Unity versions

- Cargo.lock
- Cargo.toml
- unity-version/Cargo.toml
- unity-version/proptest-regressions/version/mod.txt
- unity-version/proptest-regressions/version/release_type.txt
- unity-version/src/lib.rs
- unity-version/src/version/mod.rs
- unity-version/src/version/release_type.rs
- unity-version/src/version/revision_hash.rs
This is a new implementation of the Unity version struct and parsing methods to represent a Unity version inside uvm. It will be used with future patches. The old representation tried to combine a normal unity version with an optional revision hash. I constructed this as a seperate type. Conversion methods are not yet available because I need to see how I will actually use both types.
> Add new sub crate unity-version

- commands/uvm/tests/cli_detect.rs
- install/uvm-install2/src/main.rs
- unity-hub/src/unity/hub/paths.rs
Due to some reason the cache location was changed with the recent update. This can and will lead to issues with older versions of uvm since the lock file location is inside the cache dir.
A simple change to restore the old location.
> Fix cache dir location

- Cargo.lock
- install/uvm-install2/Cargo.toml
- install/uvm-install2/src/install/utils.rs
- install/uvm-install2/src/lib.rs
The locking logic had a slight bug as it treats all types of errors equally. But we only need to check for already locked type of an error. I think in praxis this would have not come up since the next call to wait_lock would failed as well. But the intention is cleaner.
> Fix locking logic

- Cargo.lock
- install/uvm-install2/Cargo.toml
- install/uvm-install2/src/install/installer/zip.rs
- install/uvm-install2/src/sys/linux/pkg.rs
- install/uvm-install2/src/sys/linux/xz.rs
- install/uvm-install2/src/sys/linux/zip.rs
- install/uvm-install2/src/sys/mac/dmg.rs
- install/uvm-install2/src/sys/mac/pkg.rs
- install/uvm-install2/src/sys/win/exe.rs
- install/uvm-install2/src/sys/win/msi.rs
There is a failing case when the installer things it should install a missing component even though the output path exists. In older versions this was used as a install marker.
We need to remove the destination now and reinstall cleanly.
> Fix removing destination before install

- Cargo.lock
- commands/uvm-generate-versions-yaml/src/main.rs
- install/uvm-install2/Cargo.toml
- unity-hub/Cargo.toml
- uvm_install_graph/Cargo.toml
- uvm_live_platform/Cargo.toml
- uvm_live_platform/src/api/fetch_release.rs
- uvm_live_platform/src/api/fetch_release_query.graphql
- uvm_live_platform/src/api/list_versions.rs
- uvm_live_platform/src/api/list_versions_query.graphql
- uvm_live_platform/src/error.rs
- uvm_live_platform/src/lib.rs
- uvm_live_platform/tests/fetch_release_integration.rs
- uvm_live_platform/tests/list_version_integration.rs
Unity has a new LTS version scheme called XLTS which means extended LTS for enterprise customer. By default these can't be listed with the graphql endpoints. One needs to provide an entitlements list to include this versions in the query. The documentation describes them as a filter but it acts more like an inclusion boolean. I also added the second valid entitlement U7_Alpha.
I also changed the builder pattern and usage so the default is more a default and not opinionated.
> Add support to list and query XLTS releases

- Cargo.lock
- uvm/Cargo.toml
- uvm/src/commands/version.rs
The version command was printing only a single version. Either the latest released version of Unity matching some filter criteria like platform, stream etc
Or the highest matching version based on a version filter + platform, stream filters etc.
I also wanted to be able to list all matched versions. So the `matching` subcommand now supports `--all` to list all matching versions. I also improved the default filtering since for macOS arm there are no released alpha / beta versions. By default I leave the platform and arch empty.
> Improve Version command

- Cargo.lock
- unity-version/src/lib.rs
- unity-version/src/version/mod.rs
- unity-version/src/version/revision_hash.rs
- uvm_detect/Cargo.toml
- uvm_detect/src/lib.rs
This patch adds new API to unity-version crate to parse version with revision hash. It also exposes the `CompleteVersion` struct to create and handle versions with revision hash included.
This new API is directly used in uvm_detect to return the new structs as well.
> Improve unity version parsing and allow to parse CompleteVersion

- unity-hub/src/error.rs
- unity-hub/src/unity/mod.rs
- uvm_install/src/error.rs
- uvm_install/src/sys/mac/arch.rs
The Unity Hub error type eats error context. So the error message will include now the error message from the source error.
Also the List Installation will error out when the requested directory doesn't exist. I seem to have un-commend the old test which was testing that this works.
> Fix Unity Hub errors and List installations

- Cargo.lock
- uvm/Cargo.toml
- uvm/src/commands/version.rs
- uvm_live_platform/Cargo.toml
- uvm_live_platform/src/api/cache.rs
- uvm_live_platform/src/api/fetch_release.rs
- uvm_live_platform/src/api/list_versions.rs
- uvm_live_platform/src/api/middleware.rs
- uvm_live_platform/src/api/mod.rs
- uvm_live_platform/src/error.rs
- uvm_live_platform/src/lib.rs
- uvm_live_platform/src/model/platform.rs
- uvm_live_platform/src/model/release.rs
- uvm_live_platform/tests/list_version_integration.rs
The requests to the graphql endpoint can take quite long depending on the query. Because of how some of the commands filter the output and how often the responses actually change it makes no sense to call the service every single time. So this patch adds a caching service which caches responses per request level.
> Add caching for live platform api

- Cargo.lock
- uvm/Cargo.toml
- uvm/src/commands/install.rs
- uvm_install/Cargo.toml
- uvm_install/src/lib.rs
- uvm_live_platform/src/model/platform.rs
With Unity 6 we can install the editor also on arm64 linux and windows distributions.
The arch types for the platform api and installation api where guarded to be arm64 supportive only on macOS.
I opened this up an also changed the way install gets called. Instead of a function I introduced a builder pattern fluent API.
I also cleaned out some pub use statements that got commited and release by accident.
> Add Windows/Linux Arm64 support
